// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXIq-O8qkgUSpaJcj_YJs564lxpTkUqf8',
    appId: '1:260986349391:web:926bbb9bbcedc398a2873a',
    messagingSenderId: '260986349391',
    projectId: 'aaelectroz-a1718',
    authDomain: 'aaelectroz-a1718.firebaseapp.com',
    databaseURL: 'https://aaelectroz-a1718-default-rtdb.firebaseio.com',
    storageBucket: 'aaelectroz-a1718.firebasestorage.app',
    measurementId: 'G-SCD4BRG63Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mVlGCfE2qmyyHq8vJLSJ5FF82udFXYU',
    appId: '1:260986349391:android:9f5f05e339d7e9c3a2873a',
    messagingSenderId: '260986349391',
    projectId: 'aaelectroz-a1718',
    databaseURL: 'https://aaelectroz-a1718-default-rtdb.firebaseio.com',
    storageBucket: 'aaelectroz-a1718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC8PDAWFedqt7XuZet2Os-m29vMHsZ5mA',
    appId: '1:260986349391:ios:01facd500a4863d1a2873a',
    messagingSenderId: '260986349391',
    projectId: 'aaelectroz-a1718',
    databaseURL: 'https://aaelectroz-a1718-default-rtdb.firebaseio.com',
    storageBucket: 'aaelectroz-a1718.firebasestorage.app',
    iosBundleId: 'com.example.aaelectrozFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC8PDAWFedqt7XuZet2Os-m29vMHsZ5mA',
    appId: '1:260986349391:ios:01facd500a4863d1a2873a',
    messagingSenderId: '260986349391',
    projectId: 'aaelectroz-a1718',
    databaseURL: 'https://aaelectroz-a1718-default-rtdb.firebaseio.com',
    storageBucket: 'aaelectroz-a1718.firebasestorage.app',
    iosBundleId: 'com.example.aaelectrozFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXIq-O8qkgUSpaJcj_YJs564lxpTkUqf8',
    appId: '1:260986349391:web:0a36eaa0da6853baa2873a',
    messagingSenderId: '260986349391',
    projectId: 'aaelectroz-a1718',
    authDomain: 'aaelectroz-a1718.firebaseapp.com',
    databaseURL: 'https://aaelectroz-a1718-default-rtdb.firebaseio.com',
    storageBucket: 'aaelectroz-a1718.firebasestorage.app',
    measurementId: 'G-SB0161DQEY',
  );
}
